version: '3.8'

services:
    # PHP и Laravel
    app:
        build:
            context: .
            dockerfile: Dockerfile
        container_name: laravel-app
        working_dir: /var/www
        volumes:
            - .:/var/www
        networks:
            - app-network

    # Nginx
    nginx:
        image: nginx:alpine
        container_name: nginx
        ports:
            - "8080:80"
        volumes:
            - .:/var/www
            - ../nginx/conf.d/:/etc/nginx/conf.d/
        networks:
            - app-network

    # MySQL
    mysql:
        image: mysql:5.7
        container_name: mysql
        environment:
            MYSQL_ROOT_PASSWORD: rootpassword
            MYSQL_DATABASE: laravel
        volumes:
            - mysql-data:/var/lib/mysql
        networks:
            - app-network

    # Composer (для установки зависимостей)
    composer:
        image: composer:2
        container_name: composer
        volumes:
            - .:/var/www
        networks:
            - app-network

networks:
    app-network:
        driver: bridge

volumes:
    mysql-data:
        driver: local
